plugin_run_before: 'False' # DO NOT change this. EVER.

wipe_database_pin: ''

db_type: 'mysql' # do not change

# Database Information 
# On practically every configuation, these values will be changed.
database:
  host: 'localhost'
  port: 3306
  database: 'disciplinex'
  user: 'disciplinexdbb'
  passphrase: 'example!'
